name: CountyTitles
version: 1.2.5-RELEASE
main: com.brennan.countytitles.CountyTitles
api-version: 1.16
commands:
  countytitles:
    description: Manage county titles
    usage: /countytitles <reload|addregion|setpos1|setpos2|title|subtitle|info|list|save|removeregion|actionbar> <regionname> [value]
    aliases: [ct, region]